version: "3.9"
services:
  fitfriends.postgres:
    image: postgres:14-alpine
    container_name: fitfriends.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - fitfriends.volume:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends

  fitfriends.pgadmin:
    image: dpage/pgadmin4
    container_name: fitfriends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - fitfriends.postgres
    networks:
      - fitfriends

volumes:
  fitfriends.volume:

networks:
  fitfriends:
      driver: bridge
