# Create new user
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
  "name": "Nick",
  "password": "12345678",
  "email": "ivnikon@mail.ru",
  "avatar": "keks.jpg",
  "sex": "male",
  "description": "This is the Keks. He is the test user",
  "location": "Удельная",
  "picture": "backgroung.png",
  "level": "профессионал",
  "trainingTypes": ["box"],
  "trainingTime": "50-80",
  "caloriesAll": 4000,
  "caloriesPerDay": 1500,
  "ready": true
}
###
# Login user
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "ivnikon@mail.ru",
  "password": "12345678"
}
###
# Get new JWT pair
POST http://localhost:3001/api/user/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjZiOWVmZC1hYzUyLTQ2ZWMtYjFjMS1jNmViODA4YTdiMTgiLCJlbWFpbCI6Iml2bmlrb25AbWFpbC5ydSIsIm5hbWUiOiJOaWNrIiwidG9rZW5JZCI6IjMyYTgzZTdkLWE1MTAtNDY5ZC04MDE0LTg3MGJiZTQ3YzgzYiIsImlhdCI6MTcyOTE4NDc1MiwiZXhwIjoxNzMxNzc2NzUyfQ.bQvLkOFGSMRZtXRjHYGnGJ83f26A02owVEWw3rQBCcw
###
# Get user by id
GET http://localhost:3001/api/user/bb6b9efd-ac52-46ec-b1c1-c6eb808a7b18
###
# Checkauth
GET  http://localhost:3001/api/user/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjZiOWVmZC1hYzUyLTQ2ZWMtYjFjMS1jNmViODA4YTdiMTgiLCJlbWFpbCI6Iml2bmlrb25AbWFpbC5ydSIsIm5hbWUiOiJOaWNrIiwiaWF0IjoxNzI5MTg0NjQ0LCJleHAiOjE3MjkxODQ5NDR9.i0X6nFGrfm4peuIeCCrLawoXsXpjmC0kxyLdy1uK3fc
###
