# Get balances for user
GET http://localhost:3001/api/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGY5NGU3YS04NWVmLTQ1MWItYjk2MC02MzQ5MTQzNTA2MTMiLCJlbWFpbCI6Iml2bmlrb240QG1haWwucnUiLCJuYW1lIjoi0J3QuNC60L7Qu9Cw0LkiLCJpYXQiOjE3MzUxNTI1NTksImV4cCI6MTczNTE1MzQ1OX0.YgSPyvmvBX-W7Lk0gXs7bLo726MkOsQljeQzocMJ5UQ
###
# Add traing to balance
POST http://localhost:3001/api/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGY5NGU3YS04NWVmLTQ1MWItYjk2MC02MzQ5MTQzNTA2MTMiLCJlbWFpbCI6Iml2bmlrb240QG1haWwucnUiLCJuYW1lIjoi0J3QuNC60L7Qu9Cw0LkiLCJpYXQiOjE3MzUxNTUxNTEsImV4cCI6MTczNTE1NjA1MX0.T-t9dFwRuPKu-Y9MaI7pfUY5yGx-vt5YoPdnOKUn7SU
Content-Type: application/json

{
  "trainingId": "a279b81b-f39c-42d5-ad0f-f82c8c50e2ac",
  "quantity": 1
}
###
# Spend trainig
PATCH http://localhost:3001/api/balance/a279b81b-f39c-42d5-ad0f-f82c8c50e2ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOGY5NGU3YS04NWVmLTQ1MWItYjk2MC02MzQ5MTQzNTA2MTMiLCJlbWFpbCI6Iml2bmlrb240QG1haWwucnUiLCJuYW1lIjoi0J3QuNC60L7Qu9Cw0LkiLCJpYXQiOjE3MzUxNTUxNTEsImV4cCI6MTczNTE1NjA1MX0.T-t9dFwRuPKu-Y9MaI7pfUY5yGx-vt5YoPdnOKUn7SU
###
